server:
    port: 8088
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml 
spring:
  datasource:
    url: jdbc:postgresql://10.61.5.60:5432/gisdb
    username: postgres
    password: hxhh
    driver-class-name: org.postgresql.Driver

logging:
  level:
#    com.geotools.gistools.dao: trace
   com.geotools.gistools.dao: DEBUG