
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    url: jdbc:postgresql://10.61.5.60:5432/gisdb
    username: postgres
    password: hxhh
    driver-class-name: org.postgresql.Driver