server:
  port: 8084
  max-http-header-size: 102400 
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
spring:
  datasource:
#    url: jdbc:postgresql://10.61.5.60:5432/sx_pwk
    password: hxhh
    url: jdbc:postgresql://10.61.5.84:5432/sx_hky
#    password: hxhh
#    url: jdbc:postgresql://localhost:5432/hxhh
#    password: 1234
    username: postgres
    driver-class-name: org.postgresql.Driver
  
  redis:
    database: 0
    host: 127.0.0.1
    password:
    timeout: 10000
    port: 6379
    jedis:
      pool:
        max-active: 0
        max-wait: -1
        max-idle: 8
        min-idle: 0

logging:
  level:
    #    com.geotools.gistools.mapper: trace
    com.geotools.gistools.mapper: DEBUG
zdy: 
   citypath: D:\gisdata\gp\mian.shp